Neos:
  ContentRepository:
    Search:
      defaultContext:
        TaxonomyIndexing: Sitegeist\Taxonomy\ElasticSearch\Eel\TaxonomyIndexingHelper
Sitegeist:
  Silhouettes:
    properties:
      taxonomyReferences:
        search:
          elasticSearchMapping:
            type: string
            index: not_analyzed
          indexing: '${TaxonomyIndexing.extractIdentifierAndParentIdentifiers(value)}'
